apiVersion: v1
kind: ConfigMap
metadata:
  name: uevent-config
  namespace: uevent
data:
  KAFKA_BROKERS: "kafka:9092"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  USER_SERVICE_URL: "http://user-service:3002"
  EVENT_SERVICE_URL: "http://event-service:3003"
  BOOKING_SERVICE_URL: "http://booking-service:3004"
  PAYMENT_SERVICE_URL: "http://payment-service:3005"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3006"
  NODE_ENV: "production"
  LOG_LEVEL: "info"
